export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const NEXT_TRACK = "NEXT_TRACK";
export const PREV_TRACK = "PREV_TRACK";
// export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";